management.endpoints.web.base-path = /monitor
management.endpoints.web.exposure.include = health,info,beans,env,metrics
management.endpoint.health.show-details = WHEN_AUTHORIZED
management.health.redis.enabled = false
management.endpoint.shutdown.enabled = true
management.endpoint.health.group.ping.include = ping


info.app.name = spring-boot-actuator
info.app.version = 1.0.0
info.app.test = test

##### port info #########
server.port = 8080
########################################################
### Thread Pool Properties
########################################################
executor.loader.pool.prefix = sfd-loader-thread-
executor.loader.pool.size.core = 20
executor.loader.pool.size.max = 40
executor.loader.pool.queueCapacity = 40

### logging, 和logback 会冲突
#logging.level.org.hibernate.SQL = debug
#logging.level.org.hibernate.stat = debug
#logging.level.org.hibernate.type = info
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder = TRACE
#logging.level.org.springframework.jdbc.core.JdbcTemplate = DEBUG
#logging.level.org.springframework.jdbc.core.StatementCreatorUtils = TRACE
#logging.level.com.richard.demo = info
#logging.level.feign=DEBUG

# redis config
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-wait=-1ms
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0


spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.generate-ddl = true
##h2 db
spring.datasource.url = jdbc:h2:mem:dbtest
spring.datasource.username = sa
spring.datasource.password = sa
spring.datasource.driverClassName = org.h2.Driver
#spring.datasource.schema = classpath:db/schema.sql
#spring.datasource.data = classpath:db/data.sql
#spring.datasource.platform = h2
#spring.datasource.continue-on-error = true
#spring.datasource.initialization-mode = embedded
spring.sql.init.mode=embedded
spring.sql.init.schema-locations=classpath:db/schema.sql
spring.sql.init.data-locations=classpath:db/data.sql
spring.h2.console.settings.web-allow-others = true
spring.h2.console.path = /h2-console
spring.h2.console.enabled = true


#??
open.ai.key=sk-NYsoG3VBKDiTuvdtC969F95aFc4f45379aD3854a93602327
open.ai.request.timeout=100000
open.ai.model=text-davinci-003
# resilience4j
resilience4j.circuitbreaker.instances.customCircuitBreaker.failure-rate-threshold=20
resilience4j.circuitbreaker.instances.customCircuitBreaker.sliding-window-size=10
resilience4j.circuitbreaker.instances.customCircuitBreaker.minimum-number-of-calls=2
resilience4j.circuitbreaker.instances.customCircuitBreaker.wait-duration-in-open-state=60s